// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAO.Models;

public partial class Address
{
    public long Id { get; set; }

    public long CustomerId { get; set; }

    public string AddressLine { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string Ward { get; set; }

    public bool? IsDefault { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}