// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAO.Models;

public partial class Payment
{
    public long Id { get; set; }

    public long OrderId { get; set; }

    public string Method { get; set; }

    public string Status { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual Order Order { get; set; }
}