// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAO.Models;

public partial class ProductSpec
{
    public long Id { get; set; }

    public long ProductId { get; set; }

    public string SpecKey { get; set; }

    public string SpecValue { get; set; }

    public virtual Product Product { get; set; }
}