// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAO.Models;

public partial class Product
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long? BrandId { get; set; }

    public long? CategoryId { get; set; }

    public decimal? Price { get; set; }

    public int? Stock { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductSpec> ProductSpecs { get; set; } = new List<ProductSpec>();

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();
}