// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace DAO.Models;

public partial class TechStoreDBContext : DbContext
{
    public TechStoreDBContext(DbContextOptions<TechStoreDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductSpec> ProductSpecs { get; set; }

    public virtual DbSet<Promotion> Promotions { get; set; }

    public virtual DbSet<PcComponentType> PcComponentTypes { get; set; }

    public virtual DbSet<PcBuild> PcBuilds { get; set; }

    public virtual DbSet<PcBuildItem> PcBuildItems { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            optionsBuilder.UseSqlServer(config.GetConnectionString("MyCnn"));
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // ── ROLE ─────────────────────────────────────────────────────
        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("role");
            entity.Property(e => e.Id).HasColumnName("id").ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(100).IsRequired().HasColumnName("name");
            entity.Property(e => e.Description).HasMaxLength(510).HasColumnName("description");
            entity.HasIndex(e => e.Name).IsUnique().HasDatabaseName("UQ_role_name");
        });

        // ── USER ──────────────────────────────────────────────────────
        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("user");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email).HasMaxLength(510).IsRequired().HasColumnName("email");
            entity.Property(e => e.PasswordHash).HasMaxLength(1000).IsRequired().HasColumnName("password_hash");
            entity.Property(e => e.RoleId).HasColumnName("role_id").HasDefaultValue(1);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasIndex(e => e.Email).IsUnique().HasDatabaseName("UQ_user_email");

            entity.HasOne(u => u.Role).WithMany(r => r.Users)
                .HasForeignKey(u => u.RoleId)
                .HasConstraintName("FK_user_role");

            entity.HasOne(u => u.Customer)
                .WithOne(c => c.User)
                .HasForeignKey<Customer>(c => c.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_customer_user");
        });

        // ── CUSTOMER ─────────────────────────────────────────────────
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("customer");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Name).HasMaxLength(510).IsRequired().HasColumnName("name");
            entity.Property(e => e.Email).HasMaxLength(510).HasColumnName("email");
            entity.Property(e => e.Phone).HasMaxLength(100).HasColumnName("phone");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasIndex(e => e.UserId).HasDatabaseName("IX_customer_user_id");
        });

        // ── ADDRESS ──────────────────────────────────────────────────
        modelBuilder.Entity<Address>(entity =>
        {
            entity.ToTable("address");
            entity.HasIndex(e => e.CustomerId, "IX_address_customer_id");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddressLine).HasMaxLength(1000).HasColumnName("address_line");
            entity.Property(e => e.City).HasMaxLength(200).HasColumnName("city");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.District).HasMaxLength(200).HasColumnName("district");
            entity.Property(e => e.IsDefault).HasDefaultValue(false).HasColumnName("is_default");
            entity.Property(e => e.Ward).HasMaxLength(200).HasColumnName("ward");

            entity.HasOne(d => d.Customer).WithMany(p => p.Addresses)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_address_customer");
        });

        // ── BRAND ────────────────────────────────────────────────────
        modelBuilder.Entity<Brand>(entity =>
        {
            entity.ToTable("brand");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name).HasMaxLength(510).HasColumnName("name");
        });

        // ── CATEGORY ─────────────────────────────────────────────────
        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("category");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name).HasMaxLength(510).HasColumnName("name");
        });

        // ── CART ─────────────────────────────────────────────────────
        modelBuilder.Entity<Cart>(entity =>
        {
            entity.ToTable("cart");
            entity.HasIndex(e => e.UserId, "IX_cart_user_id");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasOne(d => d.User).WithMany(p => p.Carts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_cart_user");
        });

        // ── CART ITEM ─────────────────────────────────────────────────
        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.ToTable("cart_item");
            entity.HasIndex(e => e.CartId, "IX_cart_item_cart_id");
            entity.HasIndex(e => e.ProductId, "IX_cart_item_product_id");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CartId).HasColumnName("cart_id");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Quantity).HasDefaultValue(1).IsRequired().HasColumnName("quantity");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.CartId)
                .HasConstraintName("FK_cart_item_cart");

            entity.HasOne(d => d.Product).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_cart_item_product");
        });

        // ── ORDERS ───────────────────────────────────────────────────
        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("orders");
            entity.HasIndex(e => e.AddressId, "IX_orders_address_id");
            entity.HasIndex(e => e.CreatedAt, "IX_orders_created_at");
            entity.HasIndex(e => e.CustomerId, "IX_orders_customer_id");
            entity.HasIndex(e => e.Status, "IX_orders_status");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddressId).HasColumnName("address_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.Status)
                .HasMaxLength(100)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)").HasColumnName("total_amount");
            entity.Property(e => e.ShippingFee)
                .HasColumnType("decimal(18, 2)")
                .HasDefaultValue(0m)
                .HasColumnName("shipping_fee");
            entity.Property(e => e.Notes).HasMaxLength(1000).HasColumnName("notes");
            entity.Property(e => e.TrackingNumber).HasMaxLength(200).HasColumnName("tracking_number");

            entity.HasOne(d => d.Address).WithMany(p => p.Orders)
                .HasForeignKey(d => d.AddressId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_orders_address");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_orders_customer");
        });

        // ── ORDER ITEM ───────────────────────────────────────────────
        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.ToTable("order_item");
            entity.HasIndex(e => e.OrderId, "IX_order_item_order_id");
            entity.HasIndex(e => e.ProductId, "IX_order_item_product_id");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)").HasColumnName("price");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Quantity).HasDefaultValue(1).IsRequired().HasColumnName("quantity");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_order_item_order");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_order_item_product");
        });

        // ── PAYMENT ──────────────────────────────────────────────────
        modelBuilder.Entity<Payment>(entity =>
        {
            entity.ToTable("payment");
            entity.HasIndex(e => e.OrderId, "IX_payment_order_id");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Method).HasMaxLength(100).HasColumnName("method");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.PaidAt).HasColumnType("datetime").HasColumnName("paid_at");
            entity.Property(e => e.Status)
                .HasMaxLength(100)
                .HasDefaultValue("pending")
                .HasColumnName("status");

            entity.HasOne(d => d.Order).WithMany(p => p.Payments)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_payment_order");
        });

        // ── PRODUCT ──────────────────────────────────────────────────
        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("product");
            entity.HasIndex(e => e.BrandId, "IX_product_brand_id");
            entity.HasIndex(e => e.CategoryId, "IX_product_category_id");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BrandId).HasColumnName("brand_id");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Name).HasMaxLength(510).HasColumnName("name");
            entity.Property(e => e.Sku).HasMaxLength(200).HasColumnName("sku");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Warranty).HasMaxLength(1000).HasColumnName("warranty");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)").HasColumnName("price");
            entity.Property(e => e.Stock).HasDefaultValue(0).HasColumnName("stock");

            entity.HasOne(d => d.Brand).WithMany(p => p.Products)
                .HasForeignKey(d => d.BrandId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_product_brand");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_product_category");

            entity.HasMany(d => d.Promotions).WithMany(p => p.Products)
                .UsingEntity<Dictionary<string, object>>(
                    "ProductPromotion",
                    r => r.HasOne<Promotion>().WithMany()
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_product_promotion_promotion"),
                    l => l.HasOne<Product>().WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_product_promotion_product"),
                    j =>
                    {
                        j.HasKey("ProductId", "PromotionId");
                        j.ToTable("product_promotion");
                        j.IndexerProperty<long>("ProductId").HasColumnName("product_id");
                        j.IndexerProperty<long>("PromotionId").HasColumnName("promotion_id");
                    });
        });

        // ── PRODUCT IMAGE ─────────────────────────────────────────────
        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.ToTable("product_image");
            entity.HasIndex(e => e.ProductId, "IX_product_image_product_id");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ImageUrl).HasMaxLength(2000).HasColumnName("image_url");
            entity.Property(e => e.ProductId).HasColumnName("product_id");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_product_image_product");
        });

        // ── PRODUCT SPEC ──────────────────────────────────────────────
        modelBuilder.Entity<ProductSpec>(entity =>
        {
            entity.ToTable("product_spec");
            entity.HasIndex(e => e.ProductId, "IX_product_spec_product_id");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.SpecKey).HasMaxLength(200).HasColumnName("spec_key");
            entity.Property(e => e.SpecValue).HasMaxLength(1000).HasColumnName("spec_value");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSpecs)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_product_spec_product");
        });

        // ── PROMOTION ────────────────────────────────────────────────
        modelBuilder.Entity<Promotion>(entity =>
        {
            entity.ToTable("promotion");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DiscountPercent).HasColumnName("discount_percent");
            entity.Property(e => e.EndDate).HasColumnType("datetime").HasColumnName("end_date");
            entity.Property(e => e.Name).HasMaxLength(510).HasColumnName("name");
            entity.Property(e => e.StartDate).HasColumnType("datetime").HasColumnName("start_date");
        });

        // ── PC COMPONENT TYPE ─────────────────────────────────────────
        modelBuilder.Entity<PcComponentType>(entity =>
        {
            entity.ToTable("pc_component_type");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name).HasMaxLength(200).IsRequired().HasColumnName("name");
            entity.Property(e => e.IsRequired).HasDefaultValue(true).IsRequired().HasColumnName("is_required");
            entity.Property(e => e.SortOrder).HasDefaultValue(0).IsRequired().HasColumnName("sort_order");
        });

        // ── PC BUILD ─────────────────────────────────────────────────
        modelBuilder.Entity<PcBuild>(entity =>
        {
            entity.ToTable("pc_build");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Name).HasMaxLength(510).HasColumnName("name");
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(18, 2)").HasColumnName("total_price");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasOne(d => d.User).WithMany(p => p.PcBuilds)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_pcbuild_user");
        });

        // ── PC BUILD ITEM ─────────────────────────────────────────────
        modelBuilder.Entity<PcBuildItem>(entity =>
        {
            entity.ToTable("pc_build_item");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BuildId).HasColumnName("build_id");
            entity.Property(e => e.ComponentTypeId).HasColumnName("component_type_id");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Quantity).HasDefaultValue(1).HasColumnName("quantity");

            entity.HasOne(d => d.Build).WithMany(p => p.PcBuildItems)
                .HasForeignKey(d => d.BuildId)
                .HasConstraintName("FK_pbi_build");

            entity.HasOne(d => d.ComponentType).WithMany(p => p.PcBuildItems)
                .HasForeignKey(d => d.ComponentTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_pbi_component_type");

            entity.HasOne(d => d.Product).WithMany()
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_pbi_product");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
